#!/usr/bin/env bash

set -euo pipefail

CLUSTER_NAME="${CLUSTER_NAME:-idp-dev}"
KUBECONTEXT="${KUBECONTEXT:-kind-${CLUSTER_NAME}}"
BACKSTAGE_NAMESPACE="${BACKSTAGE_NAMESPACE:-backstage-local}"
SERVICE_ACCOUNT_NAME="${SERVICE_ACCOUNT_NAME:-backstage-kubernetes}"
SERVICE_ACCOUNT_SECRET_NAME="${SERVICE_ACCOUNT_SECRET_NAME:-backstage-kubernetes-token}"
CLUSTER_CONFIG_NAME="${CLUSTER_CONFIG_NAME:-local-kind}"
CATALOG_ENTITY_URL="${CATALOG_ENTITY_URL:-https://github.com/Siddhant412/payments-api/blob/main/catalog-info.yaml}"

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT_DIR=$(cd "${SCRIPT_DIR}/../../.." && pwd)
APP_CONFIG_LOCAL="${ROOT_DIR}/backstage/app-config.local.yaml"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

require_command kubectl

if ! kubectl --context "${KUBECONTEXT}" cluster-info >/dev/null 2>&1; then
  cat <<EOF >&2
Kubernetes context '${KUBECONTEXT}' is not reachable.
Create the local cluster first:
  ./platform/bootstrap/bootstrap-local.sh
EOF
  exit 1
fi

kubectl --context "${KUBECONTEXT}" create namespace "${BACKSTAGE_NAMESPACE}" --dry-run=client -o yaml | kubectl --context "${KUBECONTEXT}" apply -f -

kubectl --context "${KUBECONTEXT}" apply -f - <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${SERVICE_ACCOUNT_NAME}
  namespace: ${BACKSTAGE_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${SERVICE_ACCOUNT_NAME}-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: ${SERVICE_ACCOUNT_NAME}
    namespace: ${BACKSTAGE_NAMESPACE}
---
apiVersion: v1
kind: Secret
metadata:
  name: ${SERVICE_ACCOUNT_SECRET_NAME}
  namespace: ${BACKSTAGE_NAMESPACE}
  annotations:
    kubernetes.io/service-account.name: ${SERVICE_ACCOUNT_NAME}
type: kubernetes.io/service-account-token
EOF

SERVER_URL=$(kubectl config view --raw --minify --context "${KUBECONTEXT}" -o jsonpath='{.clusters[0].cluster.server}')
CA_DATA=$(kubectl config view --raw --minify --context "${KUBECONTEXT}" -o jsonpath='{.clusters[0].cluster.certificate-authority-data}')

TOKEN=""
for _ in $(seq 1 30); do
  TOKEN=$(kubectl --context "${KUBECONTEXT}" -n "${BACKSTAGE_NAMESPACE}" get secret "${SERVICE_ACCOUNT_SECRET_NAME}" -o go-template='{{ index .data "token" | base64decode }}' 2>/dev/null || true)
  if [[ -n "${TOKEN}" ]]; then
    break
  fi
  sleep 1
done

if [[ -z "${TOKEN}" ]]; then
  echo "Timed out waiting for service account token secret '${SERVICE_ACCOUNT_SECRET_NAME}'" >&2
  exit 1
fi

if [[ -s "${APP_CONFIG_LOCAL}" ]]; then
  cp "${APP_CONFIG_LOCAL}" "${APP_CONFIG_LOCAL}.bak"
fi

cat > "${APP_CONFIG_LOCAL}" <<EOF
# Generated by ./platform/bootstrap/backstage/configure-local-kubernetes.sh
catalog:
  locations:
    # Keep base catalog locations here because arrays replace, not merge,
    # across app-config.yaml and app-config.local.yaml.
    - type: file
      target: ../../../platform/catalog/all.yaml
    - type: file
      target: ../../../platform/templates/node-api/template.yaml
      rules:
        - allow: [Template]
    - type: url
      target: ${CATALOG_ENTITY_URL}

kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - name: ${CLUSTER_CONFIG_NAME}
          title: Local kind
          url: ${SERVER_URL}
          authProvider: serviceAccount
          serviceAccountToken: ${TOKEN}
          caData: ${CA_DATA}
          skipTLSVerify: false
          skipMetricsLookup: true
EOF

cat <<EOF

Wrote ${APP_CONFIG_LOCAL}

Next steps:
  1. cd backstage
  2. PATH=/opt/homebrew/bin:\$PATH yarn backstage-cli config:check
  3. PATH=/opt/homebrew/bin:\$PATH yarn start
  4. Open the payments-api entity and view the Kubernetes tab
EOF
