apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes
  annotations:
    pod-policies.kyverno.io/autogen-controllers: Deployment
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-liveness-and-readiness
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - dev
                - staging
      validate:
        message: "All containers in platform namespaces must define livenessProbe and readinessProbe."
        foreach:
          - list: request.object.spec.containers[]
            deny:
              conditions:
                any:
                  - key: livenessProbe
                    operator: AllNotIn
                    value: "{{ element.keys(@)[] }}"
                  - key: readinessProbe
                    operator: AllNotIn
                    value: "{{ element.keys(@)[] }}"
